// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using dizajn_Projekti.Database;

#nullable disable

namespace dizajn_Projekti.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    [Migration("20260916174210_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("dizajn_Projekti.Models.ContactModel", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ContactId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("dizajn_Projekti.Models.DoktoriModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataELindjes")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Emri")
                        .HasColumnType("text");

                    b.Property<string>("NumriTel")
                        .HasColumnType("text");

                    b.Property<int?>("Pervoja")
                        .HasColumnType("integer");

                    b.Property<string>("PhotoFileName")
                        .HasColumnType("text");

                    b.Property<string>("Specializimi")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doktori");
                });

            modelBuilder.Entity("dizajn_Projekti.Models.EmergencyModel", b =>
                {
                    b.Property<int>("Id_E")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_E"));

                    b.Property<int>("Doctor")
                        .HasColumnType("integer");

                    b.Property<string>("NumriKontaktit")
                        .HasColumnType("text");

                    b.Property<int>("Patient")
                        .HasColumnType("integer");

                    b.Property<string>("Pershkrimi")
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.HasKey("Id_E");

                    b.HasIndex("Doctor");

                    b.HasIndex("Patient");

                    b.ToTable("EmergencyModel");
                });

            modelBuilder.Entity("dizajn_Projekti.Models.InfermjeriModel", b =>
                {
                    b.Property<int>("Id_i")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_i"));

                    b.Property<DateTime?>("DataELindjes")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Departamenti")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Emri")
                        .HasColumnType("text");

                    b.Property<string>("Gjinia")
                        .HasColumnType("text");

                    b.Property<string>("Mbiemri")
                        .HasColumnType("text");

                    b.Property<string>("NumriTel")
                        .HasColumnType("text");

                    b.Property<string>("PhotoFile")
                        .HasColumnType("text");

                    b.Property<string>("Pozita")
                        .HasColumnType("text");

                    b.Property<int?>("VitetPune")
                        .HasColumnType("integer");

                    b.HasKey("Id_i");

                    b.ToTable("Infermjeri");
                });

            modelBuilder.Entity("dizajn_Projekti.Models.NurseScheduleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("interval");

                    b.Property<int>("NurseId")
                        .HasColumnType("integer");

                    b.Property<int>("Shift")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("NurseId", "DayOfWeek", "Shift")
                        .IsUnique();

                    b.ToTable("NurseSchedules");
                });

            modelBuilder.Entity("dizajn_Projekti.Models.PacientiModel", b =>
                {
                    b.Property<int>("Id_P")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_P"));

                    b.Property<DateTime?>("DataELindjes")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Emri")
                        .HasColumnType("text");

                    b.Property<string>("Gjinia")
                        .HasColumnType("text");

                    b.Property<string>("Mbiemri")
                        .HasColumnType("text");

                    b.Property<int?>("NumriTel")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id_P");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Pacienti");
                });

            modelBuilder.Entity("dizajn_Projekti.Models.RekordModel", b =>
                {
                    b.Property<int>("Id_Rek")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Rek"));

                    b.Property<string>("Diagnoza")
                        .HasColumnType("text");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("Id_P")
                        .HasColumnType("integer");

                    b.Property<string>("Receta")
                        .HasColumnType("text");

                    b.Property<string>("Rezultatet")
                        .HasColumnType("text");

                    b.HasKey("Id_Rek");

                    b.HasIndex("DoctorId");

                    b.HasIndex("Id_P");

                    b.ToTable("Rekord");
                });

            modelBuilder.Entity("dizajn_Projekti.Models.ReservationModel", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReservationId"));

                    b.Property<int>("Doctor")
                        .HasColumnType("integer");

                    b.Property<int>("Patient")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReservationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReservationTime")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("ReservationId");

                    b.HasIndex("Doctor");

                    b.HasIndex("Patient");

                    b.ToTable("ReservationModel");
                });

            modelBuilder.Entity("dizajn_Projekti.Models.ReviewModel", b =>
                {
                    b.Property<int>("Id_R")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_R"));

                    b.Property<int>("Id_P")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewText")
                        .HasColumnType("text");

                    b.HasKey("Id_R");

                    b.HasIndex("Id_P");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("dizajn_Projekti.Models.SherbimiModel", b =>
                {
                    b.Property<int>("Id_S")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_S"));

                    b.Property<string>("Emri")
                        .HasColumnType("text");

                    b.Property<string>("Pershkrimi")
                        .HasColumnType("text");

                    b.Property<string>("Stafi")
                        .HasColumnType("text");

                    b.HasKey("Id_S");

                    b.ToTable("Sherbimi");
                });

            modelBuilder.Entity("dizajn_Projekti.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserRole")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("dizajn_Projekti.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("dizajn_Projekti.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dizajn_Projekti.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("dizajn_Projekti.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dizajn_Projekti.Models.DoktoriModel", b =>
                {
                    b.HasOne("dizajn_Projekti.Models.User", null)
                        .WithMany("Doktori")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("dizajn_Projekti.Models.EmergencyModel", b =>
                {
                    b.HasOne("dizajn_Projekti.Models.DoktoriModel", "DoctorNavigation")
                        .WithMany()
                        .HasForeignKey("Doctor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dizajn_Projekti.Models.PacientiModel", "PatientNavigation")
                        .WithMany()
                        .HasForeignKey("Patient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DoctorNavigation");

                    b.Navigation("PatientNavigation");
                });

            modelBuilder.Entity("dizajn_Projekti.Models.NurseScheduleModel", b =>
                {
                    b.HasOne("dizajn_Projekti.Models.InfermjeriModel", "Nurse")
                        .WithMany()
                        .HasForeignKey("NurseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nurse");
                });

            modelBuilder.Entity("dizajn_Projekti.Models.PacientiModel", b =>
                {
                    b.HasOne("dizajn_Projekti.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("dizajn_Projekti.Models.RekordModel", b =>
                {
                    b.HasOne("dizajn_Projekti.Models.DoktoriModel", "Doktori")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dizajn_Projekti.Models.PacientiModel", "Pacienti")
                        .WithMany()
                        .HasForeignKey("Id_P")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doktori");

                    b.Navigation("Pacienti");
                });

            modelBuilder.Entity("dizajn_Projekti.Models.ReservationModel", b =>
                {
                    b.HasOne("dizajn_Projekti.Models.DoktoriModel", "DoctorNavigation")
                        .WithMany()
                        .HasForeignKey("Doctor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dizajn_Projekti.Models.PacientiModel", "PatientNavigation")
                        .WithMany()
                        .HasForeignKey("Patient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DoctorNavigation");

                    b.Navigation("PatientNavigation");
                });

            modelBuilder.Entity("dizajn_Projekti.Models.ReviewModel", b =>
                {
                    b.HasOne("dizajn_Projekti.Models.PacientiModel", "Pacienti")
                        .WithMany()
                        .HasForeignKey("Id_P")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pacienti");
                });

            modelBuilder.Entity("dizajn_Projekti.Models.User", b =>
                {
                    b.Navigation("Doktori");
                });
#pragma warning restore 612, 618
        }
    }
}
